// lib/services/data_umum_pkk_service.dart
// ✅ HYBRID: API + method lama (autoGenerateFromRekap) + token opsional

import 'dart:convert';
import 'package:shared_preferences/shared_preferences.dart';
import '../models/data_umum_pkk.dart';
import '../models/data_keluarga_dasawisma.dart';
import 'data_keluarga_dasawisma_service.dart';
import 'api_service.dart';

class DataUmumPkkService {
  static final DataUmumPkkService _instance = DataUmumPkkService._internal();
  factory DataUmumPkkService() => _instance;
  DataUmumPkkService._internal();

  final ApiService _api = ApiService();

  static const String _cacheKey = 'cache_data_umum_pkk_v1';
  List<DataUmumPkkItem> _cache = [];
  DateTime? _lastFetch;

  // ============================================================
  // GET — dari API
  // ============================================================
  Future<List<DataUmumPkkItem>> getAll({
    String? tahun,
    String? level,
    int? wilayahId,
    String? search,
  }) async {
    try {
      final rawList = await _api.getDataUmumPkk(
        tahun: tahun,
        level: level,
        wilayahId: wilayahId,
        search: search,
      );
      final list = rawList.map((e) => DataUmumPkkItem.fromJson(e)).toList();
      _cache = list;
      _lastFetch = DateTime.now();
      await _saveToCache(list);
      return list;
    } catch (e) {
      if (_cache.isEmpty) {
        await _loadFromCache();
      }
      await _removeOrphanedAutoGeneratedItems();
      if (_cache.isNotEmpty) return _cache;
      rethrow;
    }
  }

  /// Ambil by level — 'desa' atau 'kecamatan'
  Future<List<DataUmumPkkItem>> getByLevel(String level) async {
    return getAll(level: level);
  }

  Future<List<DataUmumPkkItem>> getByTahun(String tahun) async {
    return getAll(tahun: tahun);
  }

  Future<DataUmumPkkItem?> getById(int id) async {
    try {
      final json = await _api.getDataUmumPkkDetail(id);
      return DataUmumPkkItem.fromJson(json);
    } catch (e) {
      return null;
    }
  }

  // ============================================================
  // SAVE — token OPSIONAL
  // ============================================================
  Future<DataUmumPkkItem> save(DataUmumPkkItem item, [String? token]) async {
    if (item.id > 0) {
      // Update
      if (token == null || token.isEmpty) {
        // Tanpa token — simpan lokal
        await _updateCache(item);
        return item;
      }
      final json = await _api.updateDataUmumPkk(item.id, item.toJson(), token);
      final updated = DataUmumPkkItem.fromJson(json);
      await _updateCache(updated);
      return updated;
    } else {
      // Create
      if (token == null || token.isEmpty) {
        // Tanpa token — simpan lokal
        final newId = DateTime.now().millisecondsSinceEpoch % 100000;
        final newItem = item.copyWith(id: newId);
        _cache.insert(0, newItem);
        await _saveToCache(_cache);
        return newItem;
      }
      final json = await _api.createDataUmumPkk(item.toJson(), token);
      final created = DataUmumPkkItem.fromJson(json);
      _cache.insert(0, created);
      await _saveToCache(_cache);
      return created;
    }
  }

  // ============================================================
  // DELETE — token OPSIONAL
  // ============================================================
  Future<void> delete(int id, [String? token]) async {
    if (token != null && token.isNotEmpty) {
      try {
        await _api.deleteDataUmumPkk(id, token);
      } catch (_) {
        // Silent — lanjut hapus lokal
      }
    }
    _cache.removeWhere((e) => e.id == id);
    await _saveToCache(_cache);
  }

  // ============================================================
  // ✅ METHOD LAMA — autoGenerateFromRekap — biar screen jalan
  // ============================================================
  Future<void> autoGenerateFromRekap(String level) async {
    final keluarga = await DataKeluargaDasawismaService().getAll();
    if (keluarga.isEmpty) return;

    final grouped = <String, List<DataKeluargaDasawisma>>{};
    for (final item in keluarga) {
      final key = (level == 'kecamatan' ? item.kecamatan : item.desa)
          .trim()
          .toLowerCase();
      if (key.isEmpty) continue;
      grouped.putIfAbsent(key, () => []).add(item);
    }

    for (final entries in grouped.values) {
      final first = entries.first;
      final kecamatan = first.kecamatan.trim();
      final desa = first.desa.trim();
      final identity = level == 'kecamatan' ? kecamatan : desa;
      final existingIdx = _cache.indexWhere(
        (e) =>
            e.level == level &&
            (level == 'kecamatan' ? e.namaDesa == identity : e.desa == identity),
      );
      final existing = existingIdx >= 0 ? _cache[existingIdx] : null;
      final dusun = entries
          .map((e) => e.dusun.trim().toLowerCase())
          .where((e) => e.isNotEmpty)
          .toSet()
          .length;
      final rw = entries.map((e) => e.rw.trim()).where((e) => e.isNotEmpty).toSet().length;
      final rt = entries.map((e) => '${e.rw.trim()}|${e.rt.trim()}').where((e) => e != '|').toSet().length;
      final dasawisma = entries
          .map((e) => e.dasaWisma.trim().toLowerCase())
          .where((e) => e.isNotEmpty)
          .toSet()
          .length;

      final item = DataUmumPkkItem(
        id: existing?.id ?? DateTime.now().millisecondsSinceEpoch % 100000,
        level: level,
        tahun: existing?.tahun ?? '2026',
        kabupaten: first.kabupaten,
        provinsi: first.provinsi,
        kecamatan: kecamatan,
        desa: desa,
        namaDusun: level == 'desa' ? first.dusun : '',
        namaDesa: level == 'kecamatan' ? identity : '',
        jumlahDusun: dusun,
        jumlahPkkRw: rw,
        jumlahPkkRt: rt,
        jumlahDasaWisma: dasawisma,
        jumlahKrt: entries.length,
        jumlahKk: entries.fold(0, (sum, e) => sum + e.jumlahKk),
        jiwaL: entries.fold(0, (sum, e) => sum + e.jumlahLakiLaki),
        jiwaP: entries.fold(0, (sum, e) => sum + e.jumlahPerempuan),
        kaderTpPkkL: existing?.kaderTpPkkL ?? 0,
        kaderTpPkkP: existing?.kaderTpPkkP ?? 0,
        kaderUmumL: existing?.kaderUmumL ?? 0,
        kaderUmumP: existing?.kaderUmumP ?? 0,
        kaderKhususL: existing?.kaderKhususL ?? 0,
        kaderKhususP: existing?.kaderKhususP ?? 0,
        sekretariatHonorerL: existing?.sekretariatHonorerL ?? 0,
        sekretariatHonorerP: existing?.sekretariatHonorerP ?? 0,
        sekretariatBantuanL: existing?.sekretariatBantuanL ?? 0,
        sekretariatBantuanP: existing?.sekretariatBantuanP ?? 0,
        keterangan: 'Auto-Isi dari Keluarga Binaan',
      );
      if (existingIdx >= 0) {
        _cache[existingIdx] = item;
      } else {
        _cache.add(item);
      }
    }
    await _saveToCache(_cache);
  }

  // ============================================================
  // CACHE
  // ============================================================
  Future<void> _saveToCache(List<DataUmumPkkItem> list) async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final raw = jsonEncode(list.map((e) => e.toJson()).toList());
      await prefs.setString(_cacheKey, raw);
    } catch (_) {}
  }

  Future<void> _loadFromCache() async {
    try {
      final prefs = await SharedPreferences.getInstance();
      final raw = prefs.getString(_cacheKey);
      if (raw != null) {
        final list = jsonDecode(raw) as List;
        _cache = list.map((e) => DataUmumPkkItem.fromJson(e)).toList();
      }
    } catch (_) {
      _cache = [];
    }
  }

  Future<void> _updateCache(DataUmumPkkItem item) async {
    final idx = _cache.indexWhere((e) => e.id == item.id);
    if (idx >= 0) {
      _cache[idx] = item;
    } else {
      _cache.insert(0, item);
    }
    await _saveToCache(_cache);
  }

  Future<void> _removeOrphanedAutoGeneratedItems() async {
    final keluarga = await DataKeluargaDasawismaService().getAll();
    final keys = keluarga
        .map((e) => '${e.desa.trim().toLowerCase()}|${e.kecamatan.trim().toLowerCase()}')
        .where((e) => e != '|')
        .toSet();
    final filtered = _cache.where((item) {
      if (!item.keterangan.toLowerCase().contains('auto-isi')) return true;
      final key = '${item.desa.trim().toLowerCase()}|${item.kecamatan.trim().toLowerCase()}';
      return keys.contains(key);
    }).toList();
    if (filtered.length != _cache.length) {
      _cache = filtered;
      await _saveToCache(_cache);
    }
  }

  Future<void> clearCache() async {
    _cache = [];
    final prefs = await SharedPreferences.getInstance();
    await prefs.remove(_cacheKey);
  }

  DateTime? get lastFetch => _lastFetch;
}
